# Can one block of except statements handle multiple exception?

k="Yes A Single Block of Except Statements handle multiple Exception ."
print(k)